apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worklog.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "worklog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worklog.replicaCount }}
  selector:
    matchLabels:
      {{- include "worklog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worklog.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 {{ include "worklog.name" . }}-postgres 5432; do echo "Waiting for PostgreSQL"; sleep 5; done']
      containers:
        - name: worklog
          image: "{{ .Values.worklog.image.repository }}:{{ .Values.worklog.image.tag }}"
          imagePullPolicy: {{ .Values.worklog.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.worklog.service.port }}
          resources:
            {{- toYaml .Values.worklog.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "worklog.name" . }}-config
          - secretRef:
              name: {{ include "worklog.name" . }}-postgres-secret