apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "worklog.fullname" . }}-pv
  labels:
    app.kubernetes.io/name: {{ include "worklog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.postgres.pv.size }}
  accessModes:
    - {{ .Values.postgres.pv.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.postgres.pv.storageClassName }}
  storageClassName: {{ .Values.postgres.pv.storageClassName }}
  {{- end }}
  hostPath:
    path: {{ .Values.postgres.hostPath | default "/mnt/data" }}
