apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "worklog.name" . }}-postgres-secret
  namespace: {{ .Values.namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  template:
    metadata:
      name: {{ include "worklog.name" . }}-postgres-secret
      namespace: {{ .Values.namespace }}
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"