apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "worklog.fullname" . }}-postgres-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  template:
    metadata:
      name: {{ include "worklog.fullname" . }}-postgres-secret
      namespace: {{ .Values.namespace }}