apiVersion: v1
kind: Service
metadata:
  name: {{ include "worklog.name" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "worklog.name" . }}
