apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "worklog.name" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "worklog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      {{- include "worklog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worklog.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "worklog.name" . }}-postgres-config
          - secretRef:
              name: {{ include "worklog.name" . }}-postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.pv.size }}
        storageClassName: {{ .Values.postgres.pv.storageClassName }}
          
