apiVersion: v1
kind: Service
metadata:
  name: to-do-service
spec:
  selector:
    app: to-do
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort
