namespace: worklog

api:
  image:
    repository: yohandiaz/worklog-api
    tag: 0.0.1
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  port: 8000

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

postgres:
  image:
    repository: postgres
    tag: 13.16-alpine
    pullPolicy: IfNotPresent

  replicaCount: 1
  port: 5432

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  host: worklog-postgres
  user: worklog
  db: worklog
  password: AgAAe6xN98/VDCl0xaRC9FFr69sNFImIcqEpjj+LK4BDGKBLTxwH9f+vUu+YRsN7wtziZbqHjH/Aq1n+gWu2afo0VFQh1QFNmzi+x2mFB106SKwWrQuhuCxWIr44WmZCm2f3nz9dMn4EI5EOq02buOMAslfwooH4QJtDlq0JGJZvgCr4VyeCLzVdp1dwfFI6zAKyv78ye14tR2//jB37FJ8KYk3JAHefzEVWcMKCqiXT6jRVGZ63eO+Px9cZgk/2jxIF1ccSpV2iLf7RFr5YM+eKK2DtQQTw02CKsFbtOUWDu9LAcbEF26mDbGlJ6MKJxQCwE26ibtHqpU4Kwh3Kdm4Hk+LC6NJTk1ef1aAMvDUksuUPh+4u1/hRF1oHoU9wr3f4l53A0ME4sCSjXMSKuPGOAHE7kTgzt0ybP2Jlf32u50BZidMTSntO310xRmHv/hLUzcbmNUznloDsvoCSU1qjvlCeVNQ1umMJ/ny2wlMk8I6InHbXWR3Aob7jwRGNldLxu7ak1p5J3dCFot4ktKf1jfSMEHDI83RXbVS2SJG6U/u9BS5AA7BIz3nl9/mKBdWpGjzEgsZhQB/T5kQhUY3rL2GVzJYYtV28IxXCPVbmmuxEszkd/fN+bIk9t9JSSnfBIwB3jH7AXB7dNGR+Rb1QLo9eo2WdhLEyz9nV63SdzQ9d8pcBWh8Vmbojppwk+e91uofNtJrYZOoUvE7whhTC+hUrFA==
  
  pv:
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    hostPath: /mnt/data
    storageClassName: worklog-storage-class
  
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  provisioner: kubernetes.io/no-provisioner

frontend:
  image:
    repository: yohandiaz/worklog-frontend
    tag: 0.0.1
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  port: 3000

  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  service:
    type: ClusterIP

  api:
    url: http://worklog-api:8000

ingress:
  namespaceOverride: "worklog"
  enabled: true
  annotations: {}
  hosts:
    # - host: worklog.yohanlab.dev
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

ingress-nginx:
  controller:
    replicaCount: 1
    service:
      type: NodePort
      nodePorts:
        http: 30080   # Expose HTTP on NodePort 30080
        https: 30443  # Optionally expose HTTPS on NodePort 30443
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
