apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worklog.name" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "worklog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "worklog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worklog.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 {{ include "worklog.name" . }}-postgres 5432; do echo "Waiting for PostgreSQL"; sleep 5; done']
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "worklog.name" . }}-api-config
          - secretRef:
              name: {{ include "worklog.name" . }}-postgres-secret