image:
  repository: yohandiaz/to-do
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: todo.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

ingress-nginx:
  controller:
    replicaCount: 1
    service:
      type: NodePort
    image:
      repository: k8s.gcr.io/ingress-nginx/controller
      tag: "v1.11.1"
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
