apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worklog.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "worklog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "worklog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worklog.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          envfrom:
            - configMapRef:
                name: {{ include "worklog.fullname" . }}-frontend-config
