apiVersion: v1
kind: Service
metadata:
  name: {{ include "worklog.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "worklog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port}}
  selector:
    {{- include "worklog.selectorLabels" . | nindent 4 }}
